name: Flat Checker

on:
  schedule:
    - cron: "*/30 * * * *"   # Runs every 10 minutes
  workflow_dispatch:      # manual run button

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install chromium
          
      - name: Run script
        env:
          MHADA_PAN: ${{ secrets.MHADA_PAN }}
          MHADA_PASSWORD: ${{ secrets.MHADA_PASSWORD }}
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_FROM_APP_PASSWORD: ${{ secrets.EMAIL_FROM_APP_PASSWORD }}
          EMAIL_TO_SCHIN: ${{ secrets.EMAIL_TO_SCHIN }}
          EMAIL_TO_JANA: ${{ secrets.EMAIL_TO_JANA }}
          LOGIN_URL: ${{ secrets.LOGIN_URL }}
        run: python mhada_checker.py
