name: MHADA Flat Checker

on:
  schedule:
    - cron: "*/60 * * * *"   # Runs every 30 minutes
  workflow_dispatch:      # manual run button

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install chromium

      - name: Run script
        run: python mhada_checker.py
